config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'locations#index'
  get '/locations/prefecture/:id', to: "location#prefecture"

  resources :users
  resources :locations do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  has_many :event_users
  has_many :users, through: :event_users

  with_options presence: true do
    validates :title
    validates :start_time
    validates :user_id
    validates :location_id
  end
end

app/models/location.rb
class Location < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アクティブハッシュ とのアソシエーション
  belongs_to_active_hash :prefecture
  # テーブルとのアソシエーション
  belongs_to :user
  has_many :events, dependent: :destroy
  # アクティブストレージとのアソシエーション
  has_one_attached :image

  with_options presence: true do
    validates :place
    validates :address
    validates :contact_address, format: { with: /\A[0-9]{10,11}\z/ }
    validates :user_id
    # prefectureの選択が「---」の時は保存できないようにする
    validates :prefecture_id, numericality: { other_than: 0, message: 'を選択してください' }
  end

  # addressから自動で緯度と経度のカラムに値を代入する
  geocoded_by :address
  after_validation :geocode
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: '福岡県' }, { id: 2, name: '佐賀県' },
    { id: 3, name: '長崎県' }, { id: 4, name: '熊本県' }, { id: 5, name: '大分県' },
    { id: 6, name: '山口県' }
  ]
  include ActiveHash::Associations
  has_many :locations
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :locations
  has_many :event_users
  has_many :events, through: :event_users
  # nameカラムのバリデーションを追加
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']  # 環境変数を読み込む記述に変更
    end
  end

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(_resource)
    root_path
  end

  # ログアウト後の遷移先
  def after_sign_out_path_for(_resource)
    root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @event = Event.new
    @location = Location.find(params[:location_id])
    @events = Event.where(location_id: @location.id)
  end

  def new
    @event = Event.new
  end

  def show
    case params[:order_sort]
    when '1'
      @location = Location.find(params[:location_id])
      @event = Event.find(params[:event_id])
      @user = User.find(params[:id])
    else
      @location = Location.find(params[:location_id])
      @event = Event.find(params[:id])
    end
  end

  def create
    @location = Location.find(params[:location_id])
    @event = @location.events.new(event_parameter)
    if @event.valid?
      @event.save
      redirect_to location_events_path, notice: '登録しました'
    else
      redirect_to location_events_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if user_signed_in? && (current_user.id == @event.user_id)
      @event.destroy
      redirect_to location_events_path(@event.location_id), notice: '削除しました'
    else
      render location_events_path(@event.location_id), notice: '削除できませんでした'
    end
  end

  private

  def event_parameter
    params.require(:event).permit(:title, :start_time).merge(user_id: current_user.id, location_id: params[:location_id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_location, only: [:edit, :show, :update, :destroy]
  before_action :my_location, only: [:edit, :destroy]

  def index
    @locations = Location.all
    @location1 = Location.where(prefecture_id: 1)
    @location2 = Location.where(prefecture_id: 2)
    @location3 = Location.where(prefecture_id: 3)
    @location4 = Location.where(prefecture_id: 4)
    @location5 = Location.where(prefecture_id: 5)
    @location6 = Location.where(prefecture_id: 6)
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.valid?
      @location.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @location.update(location_params)
      render :update
    else
      redirect_to :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to root_path
  end

  private

  def location_params
    params.require(:location).permit(:place, :address, :contact_address, :fee, :info, :image, :prefecture_id, :latitude,
                                     :longitude).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_location
    @location = Location.find(params[:id])
  end

  def my_location
    @location.user_id == current_user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user
  def show
    @events = Event.where(user_id: current_user.id)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user.id == current_user.id
  end

  private

  def user_events_params
    params.require(:location).permit(:place, :address, :contact_address, :fee, :info, :image, :prefecture_id, :latitude,
                                     :longitude).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<%= render partial: 'shared/events_index' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
  <div class="show-title">出店予定詳細</div>
  <p class="p1">
    <%= @event.title %>
  </p>

  <p class="p2">
    <strong>日時</strong>
    <%= @event.start_time.strftime("%m-%d") %>
  </p>

  <div class="link-btn">
  <% if user_signed_in? && current_user.id == @event.user_id %> 
    <%= link_to '削除', location_event_path(@event.id), method: :delete, data: { confirm: '削除しますか?' } %>
  <% end %> 
    <%= link_to '戻る', location_events_path %>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodTruck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@1,800&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  
  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <%= render 'shared/header' %>
    <%= render 'shared/toast' %>
    <div class="background">
      <div class="rgba">
        <div id="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/locations/edit.html.erb
<%= form_with model: @location, method: :patch, local: true do |f| %>
  <div class="new-location">
  <h1 class="form-title">出店場所 編集</h1>
    <%# 場所の画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        場所の画像
      </div>
      <div class="click-upload">
        <p>
          クリックして画像をアップロード
        </p>
        <%= f.file_field :image, id:"item_image" %>
      </div>
    </div>
    <%# 場所の名前 %>
    <div class="weight-bold-text">
      場所名
      <span class="indispensable">*必須</span>
    </div>
    <%= f.text_field :place, class:"location-place", placeholder:"(例) PayPayドーム前", maxlength:"30" %>
    <%# 住所 %>
    <div class="weight-bold-text">
      住所
      <span class="indispensable">*必須</span>
    </div>
    <%# 県のプルダウン %>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %>
    <%= f.text_field :address, class:"location-address", placeholder:"(例) 福岡市中央区天神1-1", maxlength:"30" %>
    <%# 連絡先 %>
    <div class="weight-bold-text">
      連絡先
      <span class="indispensable">*必須</span>
    </div>
    <%= f.text_field :contact_address, class:"location-contact-address", placeholder:"ハイフン除く", maxlength:"11" %>
    <%# 出店料 %>
    <div class="weight-bold-text">
      出店料
    </div>
    <%= f.text_field :fee, class:"location-fee", placeholder:"(例) 一律500円,売上の15%など", maxlength:"30" %>
    <%# その他情報 %>
    <div class="weight-bold-text">
      その他情報
    </div>
    <%= f.text_area :info, class:"location-info", placeholder:"(例) 客層,ピーク時間帯,注意事項", maxlength:"100" %>
    <%# 登録ボタン %>
    <%= f.submit '変更する', class: "button" %>
  </div>
<% end %>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="キッチンカー 場所登録・管理アプリ">
</head>
<body>
    <div class="main-image">
      <div class="bkRGBA">
        <p class="main-text">~ FOOD TRUCK ~</p>
        <p class="main-text2">場所の共有 & 空き状況の確認</p>
      </div>
    </div>
    <div id="contents">
      <section id="new">
        <h2>出店場所一覧</h2>
          <%# 投稿がある場合は、eachメゾッドで一覧表示する %>
          <div class="location-lists">
            <div class="prefecture-group">福岡県</div>
            <div class="location-list">
            <% @location1.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
            <div class="prefecture-group">佐賀県</div>
            <div class="location-list">
            <% @location2.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
            <div class="prefecture-group">長崎県</div>
            <div class="location-list">
            <% @location3.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
            <div class="prefecture-group">熊本県</div>
            <div class="location-list">
            <% @location4.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
            <div class="prefecture-group">大分県</div>
            <div class="location-list">
            <% @location5.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
            <div class="prefecture-group">山口県</div>
            <div class="location-list">
            <% @location6.each do |location| %> 
              <%= link_to location_path(location.id) do  %>
                <div class="location-image-content">
                  <%= image_tag location.image.variant(resize: '200x200'), class: 'location-image' if location.image.attached? %>
                  <%= location.place %>
                </div>
              <% end %>
            <% end %>
            </div>
          </div>
      </section>
    </div>
    <!--/contents-->
    <footer> <small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small> <span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span> </footer>
</body>
</html>

app/views/locations/link.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>初心者向けホームページテンプレート tp_beginner5</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="ここにサイト説明を入れます">
  <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
  <link rel="stylesheet" href="css/style.css">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
  <div id="container">
    <header>
      <nav id="menubar">
      <ul>
        <li><a href="index.html">ログイン</a></li>
        <li><a href="about.html">新規登録</a></li>
      </ul>
    </nav>
    </header>
    <h1 id="logo"><a href="index.html"><img src="images/logo.png" alt="SAMPLE SITE"></a></h1> 
    <div id="contents">
      <section>
        <h2>リンク</h2>
        <table class="ta1">
          <caption>見出しが必要であればここを使います</caption>
          <tr>
            <th><a href="#">サイト名</a><br> <img src="images/mainimg.jpg" alt=""></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
          <tr>
            <th><a href="#">サイト名</a></th>
            <td>ここに説明など入れて下さい。サンプルテキスト。</td>
          </tr>
        </table>
      </section>
    </div>
    <!--/contents-->
    <footer> <small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small> <span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span> </footer>
  </div>
  <!--/container-->
</body>
</html>

app/views/locations/new.html.erb
<%= form_with model: @location, method: :post, local: true do |f| %>
  <div class="new-location">
  <h1 class="form-title">出店場所 新規投稿</h1>
    <%# 場所の画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        場所の画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item_image" %>
      </div>
    </div>
    <%# 場所の名前 %>
    <div class="weight-bold-text">
      場所名
      <span class="indispensable">*必須</span>
    </div>
    <%= f.text_field :place, class:"location-place", placeholder:"(例) PayPayドーム前", maxlength:"30" %>
    <%# 住所 %>
    <div class="weight-bold-text">
      住所
      <span class="indispensable">*必須</span>
    </div>
    <%= f.text_field :address, class:"location-address", placeholder:"(例) 福岡市中央区地行浜２丁目２−２", maxlength:"50" %>
    <%# 連絡先 %>
    <div class="weight-bold-text">
      連絡先
      <span class="indispensable">*必須</span>
    </div>
    <%= f.text_field :contact_address, class:"location-contact-address", placeholder:"*必須 (例) 012-1234-1234", maxlength:"11" %>
    <%# 出店料 %>
    <div class="weight-bold-text">
      出店料
    </div>
    <%= f.text_field :fee, class:"location-fee", placeholder:"(例) 一律500円,売上の15%など", maxlength:"30" %>
    <%# その他情報 %>
    <div class="weight-bold-text">
      その他情報
    </div>
    <%= f.text_field :info, class:"location-info", placeholder:"(例) 客層,ピークの時間帯,気を付けることなど", maxlength:"50" %>
    <%# 登録ボタン %>
    <%= f.submit '登録する', class: "button" %>
  </div>
<% end %>

app/views/locations/show.html.erb
<div class="contents-row">
    <div class="more">
     <%= image_tag @location.image.variant(resize: '500x500'), class: 'location-image' if @location.image.attached? %>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_location_path(@location.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', location_path(@location.id), method: :delete, data: { confirm: '削除しますか?' }  %>
        </li>
      </ul>
    </div>
    <div class="location-show">
      <div class="place"><%= @location.place %></div>
        <ul class="show-lists">
          <li>住所・・・・・・<%= @location.address %></li>
          <li>連絡先・・・・・<%= @location.contact_address %></li>
          <li>出店料・・・・・<%= @location.fee %></li>
          <li>その他情報・・・<%= @location.info %></li>
        </ul>
    </div>
  </div>


  <%# カレンダー表示 %>
  <div class="events-link">
    <%= image_tag "eventicon.png", class:"event-icon" %><%= link_to '出店状況の確認', location_events_path(@location.id) %>
  </div>
  <%# JavaScriptでGoogleMapを表示する %>
  <!-- 住所表示エリア -->
  <p class="this-address"><%= @location.address %></p>

  <!-- Googleマップ表示エリア(地図を表示) -->
  <div id="map"></div>

  <!-- Googleマップ表示用の Javascript -->
  <script>
    function initMap(){
      // 地図の位置情報(緯度・経度)を取得
      let mapPosition = {lat: <%= @location.latitude || 0 %> , lng: <%= @location.longitude || 0 %> };
      let map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: mapPosition
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      let contentString = '【住所】<%= @location.address %>';
      let infowindow = new google.maps.InfoWindow({
        content: contentString
      });

      let marker = new google.maps.Marker({
        position: mapPosition,
        map: map,
        title: contentString
      });

      marker.addListener('click', function(){
        infowindow.open(map, marker);
      });
    }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>
</div>

app/views/locations/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_events_index.html.erb
  <p id="notice"><%= notice %></p>

  <div class="toppage">
  <div class="event-location"><%= image_tag "目的地アイコン3.png", class:"location-ev-icon" %><%= @location.place %></div>
  <%= form_with model: [@location, @event], local: true do |form| %>
    <div class="title">
      <div class="form-tag">出店予定のキッチンカー名を入力してください</div>
      <%= form.text_field :title %>
    </div>
      <div class="time">
      <div class="form-tag">出店日時を選択してください</div>
      <%= form.datetime_select :start_time %>
    </div>
  <div class="submit">
      <%= form.submit %>
  </div>
  <% end %>
  </div>
  <div class="col-md-8">
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to event.title.truncate(5), location_event_path(@location.id, event.id) %>
      </div>
    <% end %>
  <% end %>
  </div>
  </div>
  </div>

app/views/shared/_header.html.erb
<header>
      <nav id="menubar">
        <h1 class="apptitle"><a href="/">FOOD TRUCK</a></h1>
        <% if user_signed_in? %>
          <div class="list">
          <%= link_to "出店場所の登録", new_location_path, class: "post" %>
          <%= link_to "マイページ", "/users/#{current_user.id}", class: "post" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "post" %>
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        <% end %>
        </div>
      </nav>
    </header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_toast.html.erb
<% if flash[:notice].present? %>
  <div class="toast">
    <div class="notice"><%= notice %></div>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="toast">
    <div class="alert"><%= alert %></div>
  </div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calender-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="subtitle"><%= @user.name %>・・・My Calender・・・</div>
  <%# カレンダー表示 %>
    <div class="col-md-8">
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to event.location.place.truncate(13), location_event_path(event_id: event.id, location_id: event.location.id, order_sort: 1) %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>